[package]
name = "tauri-macros"
version = "1.0.0-beta.5"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "os", "filesystem", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Macros for the tauri crate."
edition = "2018"
exclude = [ ".license_template", "CHANGELOG.md", "/target" ]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = [ "full" ] }
tauri-codegen = { version = "1.0.0-beta.4", path = "../tauri-codegen" }

[features]
custom-protocol = [ ]
